"""Cookie-jar-backed client for the My O2 (UK) ecare dashboard.

The My O2 portal is gated by a PingOne DaVinci login that requires a
device-fingerprint payload generated by a JavaScript SDK in the
browser. We can't reproduce that login in pure Python, and we can't run
a real browser inside Home Assistant OS (the Python environment is
musl-based, which Playwright doesn't support).

Instead the user logs into ``https://www.o2.co.uk/ecare/home`` once in
their normal browser, copies the request cookies, and pastes them into
the integration's config. We poll the dashboard with those cookies and
parse the inline RSC payload. When the cookies expire, the dashboard
responds with a sign-in page; we surface that as an auth error so the
user can paste a fresh set.
"""

from __future__ import annotations

from http.cookies import SimpleCookie

from aiohttp import ClientError, ClientSession

from .const import DASHBOARD_URL, USER_AGENT


class O2ApiError(Exception):
    """Generic API failure (transient: network, 5xx, parsing)."""


class O2AuthError(O2ApiError):
    """Cookies are missing/invalid/expired."""


class O2ApiClient:
    """Cookie-jar-backed client for the My O2 ecare dashboard."""

    def __init__(self, session: ClientSession, cookies: dict[str, str]) -> None:
        self._session = session
        self._cookies = dict(cookies)

    @property
    def cookie_count(self) -> int:
        return len(self._cookies)

    async def async_get_dashboard_html(self) -> str:
        """Fetch the ecare dashboard HTML, raising on auth failure."""
        if not self._cookies:
            raise O2AuthError("No cookies configured")

        try:
            async with self._session.get(
                DASHBOARD_URL,
                headers={"User-Agent": USER_AGENT},
                cookies=self._cookies,
                allow_redirects=True,
            ) as resp:
                if resp.status >= 500:
                    raise O2ApiError(f"Dashboard returned {resp.status}")
                html = await resp.text()
                final_url = str(resp.url)
        except ClientError as err:
            raise O2ApiError(f"Network error fetching dashboard: {err}") from err

        if _looks_like_login_page(html, final_url):
            raise O2AuthError(
                "Session has expired – paste fresh cookies in the integration's options."
            )
        return html


def parse_cookie_string(raw: str) -> dict[str, str]:
    """Parse cookies pasted from DevTools.

    Accepts either:
      * the value of a ``Cookie:`` header (``name=value; name=value``);
      * lines of ``name=value`` pairs;
      * leading ``Cookie:`` prefix is tolerated.
    """
    if not raw:
        return {}
    text = raw.strip()
    # Tolerate "Cookie: ..." prefix and a stray trailing semicolon.
    if text.lower().startswith("cookie:"):
        text = text[len("cookie:") :].strip()
    text = text.replace("\n", ";").replace("\r", "")

    jar: SimpleCookie = SimpleCookie()
    jar.load(text)
    return {key: morsel.value for key, morsel in jar.items()}


def _looks_like_login_page(html: str, final_url: str) -> bool:
    """The dashboard always contains an ``__next_f`` RSC stream and a
    canonical ``ecare/home`` URL. Any other response means we got
    redirected to sign-in."""
    if "/ecare/home" not in final_url:
        return True
    if "__next_f" not in html:
        return True
    return any(marker in html for marker in ("daVinciResponseForm", "auth/signin", '"PingOne"'))
