"""Async client for the My O2 (UK) ecare dashboard.

Authentication is gated by a PingOne DaVinci flow that requires a
device-fingerprint payload generated by the PingOne Signals (``skrisk``)
JavaScript SDK. We can't reproduce that in pure Python, so we drive the
login with a real Chromium via Playwright, persist the resulting cookies
to disk, and from then on poll the dashboard with plain ``aiohttp``.

When the cookies expire (the dashboard responds with a redirect to the
sign-in page) we re-launch Playwright to refresh them.
"""

from __future__ import annotations

import asyncio
import json
import logging
from pathlib import Path
from typing import Any

import aiohttp
from aiohttp import ClientError, ClientSession

from .const import DASHBOARD_URL, USER_AGENT

_LOGGER = logging.getLogger(__name__)

# How long Playwright is allowed to spend on a full login.
_LOGIN_TIMEOUT_MS = 90_000


class O2ApiError(Exception):
    """Generic API failure (transient: network, 5xx, parsing)."""


class O2AuthError(O2ApiError):
    """Authentication failed."""


class O2ApiClient:
    """Cookie-jar-backed client for the My O2 ecare dashboard."""

    def __init__(
        self,
        session: ClientSession,
        username: str,
        password: str,
        storage_path: Path,
    ) -> None:
        self._session = session
        self._username = username
        self._password = password
        self._storage_path = storage_path
        self._jar: aiohttp.CookieJar | None = None
        self._lock = asyncio.Lock()

    @property
    def username(self) -> str:
        return self._username

    async def async_login(self) -> None:
        """Run the full Playwright login and persist cookies."""
        async with self._lock:
            await self._login_locked()

    async def async_get_dashboard_html(self) -> str:
        """Return the raw HTML of the ecare dashboard, logging in if needed."""
        async with self._lock:
            if self._jar is None and not self._load_cookies_from_disk():
                await self._login_locked()

            html = await self._fetch_dashboard()
            if _looks_like_login_page(html):
                _LOGGER.info("O2 UK session expired; re-logging in")
                await self._login_locked()
                html = await self._fetch_dashboard()
                if _looks_like_login_page(html):
                    raise O2AuthError("Dashboard still gated after re-login")
            return html

    # --- internals ---------------------------------------------------

    async def _login_locked(self) -> None:
        storage = await asyncio.get_running_loop().run_in_executor(
            None, _run_playwright_login, self._username, self._password
        )
        self._apply_storage(storage)
        self._save_cookies_to_disk(storage)

    async def _fetch_dashboard(self) -> str:
        try:
            async with self._session.get(
                DASHBOARD_URL,
                headers={"User-Agent": USER_AGENT},
                cookies=self._cookie_dict(),
                allow_redirects=True,
            ) as resp:
                if resp.status >= 500:
                    raise O2ApiError(f"Dashboard returned {resp.status}")
                return await resp.text()
        except ClientError as err:
            raise O2ApiError(f"Network error fetching dashboard: {err}") from err

    def _apply_storage(self, storage: dict[str, Any]) -> None:
        jar = aiohttp.CookieJar()
        # Playwright storage_state has a top-level "cookies" list.
        cookies = storage.get("cookies", [])
        # We sidestep aiohttp's set_cookie-via-response helper and use a
        # plain dict the next request will send back. That's enough for
        # the dashboard, which only needs the session cookies on
        # *.o2.co.uk / www.o2.co.uk.
        self._jar = jar
        self._cookies_cache = {c["name"]: c["value"] for c in cookies}

    def _cookie_dict(self) -> dict[str, str]:
        return getattr(self, "_cookies_cache", {}) or {}

    def _load_cookies_from_disk(self) -> bool:
        if not self._storage_path.exists():
            return False
        try:
            storage = json.loads(self._storage_path.read_text())
        except (OSError, json.JSONDecodeError):
            return False
        self._apply_storage(storage)
        return bool(self._cookie_dict())

    def _save_cookies_to_disk(self, storage: dict[str, Any]) -> None:
        try:
            self._storage_path.parent.mkdir(parents=True, exist_ok=True)
            self._storage_path.write_text(json.dumps(storage))
        except OSError as err:
            _LOGGER.warning("Could not persist O2 UK cookies: %s", err)


def _looks_like_login_page(html: str) -> bool:
    """Heuristic: dashboard HTML always contains ``__next_f``; login pages
    contain DaVinci or PingOne markers."""
    if "__next_f" in html and "ecare/home" in html:
        return False
    return any(marker in html for marker in ("daVinciResponseForm", "PingOne", "/signin"))


def _run_playwright_login(username: str, password: str) -> dict[str, Any]:
    """Synchronous Playwright login. Returns Playwright storage_state.

    Raises :class:`O2AuthError` on failure. This runs in an executor
    because Playwright's sync API uses threads.
    """
    try:
        from playwright.sync_api import (  # noqa: PLC0415
            TimeoutError as PlaywrightTimeout,
        )
        from playwright.sync_api import (
            sync_playwright,
        )
    except ImportError as err:  # pragma: no cover
        raise O2ApiError(
            "Playwright is not installed. Run 'pip install playwright' "
            "and 'playwright install chromium'."
        ) from err

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        try:
            context = browser.new_context(user_agent=USER_AGENT)
            page = context.new_page()
            page.set_default_timeout(_LOGIN_TIMEOUT_MS)

            try:
                page.goto("https://accounts.o2.co.uk/signin")

                # Identifier-first form
                page.wait_for_selector('input[name="subject"]')
                page.fill('input[name="subject"]', username)
                page.click('button[type="submit"], input[type="submit"]')

                # Password form (rendered by DaVinci widget)
                page.wait_for_selector('input[type="password"]', timeout=_LOGIN_TIMEOUT_MS)
                page.fill('input[type="password"]', password)
                page.click('button[type="submit"], input[type="submit"]')

                # Wait until we land on the ecare dashboard.
                page.wait_for_url("**/ecare/home**", timeout=_LOGIN_TIMEOUT_MS)
            except PlaywrightTimeout as err:
                raise O2AuthError(f"Login timed out: {err}") from err

            return dict(context.storage_state())
        finally:
            browser.close()
